### ISSUE TITLE
Not properly explained the steps.

### ISSUE THREAD

**Issue by prashantchahal26** [MiteshSharma/JMeterUserLoadTest#1]
Just a screenshot of the sub-topic is not able to help. Could you please elaborate what all fields we have yo fill and what to fill after every step of yours.
 - Add a HTTP Request Default
 - Add HTTP Request Sampler
Can't exactly what to fill in these boxes after clicking on these options?

**Comment by MiteshSharma** [comment]
@prashantchahal26 Explained most items in this article: https://itnext.io/load-testing-using-apache-jmeter-af189dd6f805 .... Please go through it and let me know if there are still some doubts.
